### ISSUE TITLE
Example not working on Android phone

### ISSUE THREAD

**Issue by jjhembd** [GlobeletJS/GlobeletJS#20]
**Describe the bug**
The [example linked from the README](https://globeletjs.org/examples/mountains/index.html) does not work at all on Android phones.

**How To Reproduce**
Go to https://globeletjs.org/examples/mountains/index.html from an Android phone

**Expected behavior**
The globe should appear similar to what it looks like on an iPhone

**Screenshots**
![image](https://user-images.githubusercontent.com/41167620/156702091-9f6b07cd-cadc-43ef-a903-5d54ea5619e5.png)

**Environment:**
 - Device: phone
 - OS: Android
 - Browser: not sure. Perhaps Android WebView, since people are loading the page from links in Slack and WhatsApp
 - GlobeletJS Version v0.1.4

**Additional context**
Earlier versions worked? Can't confirm. WebGL2 is working fine on one test user's phone
![image](https://user-images.githubusercontent.com/41167620/156702476-116fa015-e402-4d2e-9716-d677734753b1.png)

**Comment by jjhembd** [comment]
Two possibilities:
- Media query problem for portrait vs landscape mode on Samsung. See https://stackoverflow.com/a/32044548/10082269
- Current example has SVG and script tags after the closing body tag

**Comment by jjhembd** [comment]
I tested on a Samsung Galaxy A03s running Android 11. The example looks fine on Chrome.

![Screenshot_20220309-124510_Chrome](https://user-images.githubusercontent.com/41167620/157510300-a9001d37-524c-4c11-8cc8-2c23400804ef.jpg)

So Android itself is not the problem. We need more details about the phones that can't load the example.

**Comment by jjhembd** [comment]
One phone that couldn't load the example was running Android 8.

I installed [Android Studio](https://developer.android.com/studio) and emulated a Galaxy Nexus running Android 8. After linking this virtual device to Google DevTools, I got errors for the following code patterns:

- [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
- [Promise.allSettled()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)

To fix this, perhaps we need to provide a transpiled bundle, using [Babel](https://babeljs.io/) or similar, to convert these patterns to an older form of JavaScript.

**Comment by jjhembd** [comment]
For context, here is the Android version distribution according to Android Studio. If we want to support >80% of Android users, we need to support version 8.

![image](https://user-images.githubusercontent.com/41167620/157533356-033f85a1-ed4e-402c-8628-ba5998c03909.png)

**Comment by jjhembd** [comment]
On a Caterpillar phone running the Brave browser on Android 8.1, the globe appears and is functional, but there is no map on it.

We traced the problem back to tile-gl. See https://github.com/GlobeletJS/tile-gl/issues/2

**Comment by jjhembd** [comment]
Meanwhile, I tried generating a transpiled GlobeletJS bundle with Babel. The result on the Caterpillar phone is the same: functional globe with no map.

**Comment by jjhembd** [comment]
After #21, it is now working on the Caterpillar phone (Brave browser, Android 8.1)
![BBD518D8-A52B-4803-901E-A87A2E607863](https://user-images.githubusercontent.com/41167620/162482108-e33230cf-48cc-4195-bd0d-ef8a51a64dc0.jpeg)

**Comment by ananya-roy** [comment]
Still not working on android 8.0

**Comment by jjhembd** [comment]
Possibly relevant issues from another project: they found gl.BLEND was not working on Samsung devices. We are setting a blend function in yawgl initContext.
https://github.com/microsoft/onnxjs/issues/145
Lots more info in the PR that fixed onnxjs:
https://github.com/microsoft/onnxjs/pull/149

**Comment by jjhembd** [comment]
I plugged a Samsung Galaxy S9 into my computer and set up USB debugging. The [satellite-view example](https://globeletjs.github.io/satellite-view/examples/stamen/) was giving the following error when compiling the fragment shader:
```
main.min.js:195 Uncaught Error: yawgl.initProgram: An error occured compiling the shader:
ERROR: 0:41: 'sampler2D' : samplers must be uniform
ERROR: 1 compilation errors.  No code generated.
```

This was coming from the sampleLOD function, which input the sampler object as a function argument.

Desktop Chrome and Safari, iOS Safari, and many Android phones had no problem with this. But other compilers apparently don't recognize that only uniforms are being passed to the function.

**Comment by jjhembd** [comment]
PR #20 updates satellite-view, to a version that always uses the global name of the sampler uniform (instead of passing it as a function argument). This should fix our remaining test phones.
